### ISSUE TITLE
Server won't start with "filesystem error"

### ISSUE THREAD

**Issue by joshuax8** [goofball222/factorio#22]
## Reporting bugs/issues

* When reporting a bug/issue:
    * Ensure that you are using the latest release.
    * Revert any custom modifications or environment varibles to insure they're not the cause.

* Please provide the following information:
    * OS/distribution version (command for your OS may differ):
    ```
    No LSB modules are available.
    Distributor ID: Ubuntu
    Description:    Ubuntu 18.04.5 LTS
    Release:        18.04
    Codename:       bionic
    ```

    * Docker version:
    ```
    Docker version 19.03.6, build 369ce74a3c
    ```

    * Labels from container:
    ```
            "Labels": {
                "org.opencontainers.image.created": "2021-03-15T19:59:50Z",
                "org.opencontainers.image.licenses": "Apache-2.0",
                "org.opencontainers.image.revision": "be20460",
                "org.opencontainers.image.source": "https://github.com/goofball222/factorio.git",
                "org.opencontainers.image.title": "Factiorio Headless Server",
                "org.opencontainers.image.url": "https://github.com/goofball222/factorio",
                "org.opencontainers.image.vendor": "The Goofball - goofball222@gmail.com",
                "org.opencontainers.image.version": "1.1.27"
            }
    ```

    * Details on how to reproduce the trouble, if available:
Server fails to start with this log message:
```
2021-03-23T19:56:25.533 <docker-entrypoint> INFO - Creating new map / save.zip in /opt/factorio/saves with settings from /opt/factorio/config/map-gen-settings.json
   0.000 Error Util.cpp:83: filesystem error: cannot make canonical path: Operation not permitted [/opt/factorio/bin/x64/../../config]
```
Even with the most basic way to start the container this happens:
```
$ docker run --name factorio -d \
    -p 34197:34197/udp \
    goofball222/factorio
```
It appears to be the same as here: https://github.com/OpenFactorioServerManager/factorio-server-manager/issues/264
They fixed it by switching the base image from Alpine to Ubuntu. Let me know if you need more info.

**Comment by joshuax8** [comment]
Please see [my fork](https://github.com/joshuax8/factorio/tree/fix/main%2Fubuntu_base_image) for a Ubuntu base image version. It looks like the problem is fixed for me by using the ubuntu base image. (I can make a pull request if desired)

**Comment by goofball222** [comment]
I finally found time to switch the base on this to debian:buster-slim. This is resolved.
