### ISSUE TITLE
[1.1.36] Max Upload flag does not work

### ISSUE THREAD

**Issue by cgomm** [goofball222/factorio#23]
## Reporting bugs/issues

* When reporting a bug/issue:
    * Ensure that you are using the latest release.
    * Revert any custom modifications or environment varibles to insure they're not the cause.

* Please provide the following information:
    * OS/distribution version (command for your OS may differ):
    ```bash
    user@host:~$ lsb_release -a
    No LSB modules are available.
    Distributor ID: Ubuntu
    Description:    Ubuntu 20.04.2 LTS
    Release:        20.04
    Codename:       focal
    ```

    * Docker version:
    IE:
    ```bash
    user@host:~$ docker --version
    Docker version 20.10.2, build 20.10.2-0ubuntu1~20.04.3
    ```

    * Labels from container:
    IE:
    ```bash
    user@host:~$ docker inspect goofball222/factorio:1.1.36
    ...
                "Labels": {
                      "org.opencontainers.image.created": "2021-07-20T16:43:54.249Z",
                      "org.opencontainers.image.description": "Factiorio Headless Server",
                      "org.opencontainers.image.licenses": "Apache-2.0",
                      "org.opencontainers.image.revision": "78139386224c8dc32392efc548a1857578391146",
                      "org.opencontainers.image.source": "https://github.com/goofball222/factorio",
                      "org.opencontainers.image.title": "Factiorio Headless Server",
                      "org.opencontainers.image.url": "https://github.com/goofball222/factorio",
                      "org.opencontainers.image.vendor": "The Goofball - goofball222@gmail.com",
                      "org.opencontainers.image.version": "1.1.36-Debian"
                  }
    ...
    ```

    * Details on how to reproduce the trouble, if available:

Hey there,

in my last attempt to reduce the networkspeed used by the factorio container on my own network I tried your config line 

```bash
"_comment_max_upload_in_kilobytes_per_second" : "optional, default value is 0. 0 means unlimited.",
  "max_upload_in_kilobytes_per_second": 10000,
```

With some quick checks I wasn't able to reduce the network upload bandwith used by the container, instead it used the full speed of aroung 26,2mbit/s up.

I am using the last version as a fixed version to prevent any auto updates in case one of the mods will not be compatible to the new version of factorio headless server.

Have a great day!

**Comment by goofball222** [comment]
I just tested the upload throttle setting on the 1.1.56-Debian image and it's working as expected. It's an entirely in-game/in-server function so if that isn't working for you it may be a mod conflict or configuration issue on your end.
