### ISSUE TITLE
Add `arm64` support.

### ISSUE THREAD

**Issue by LWJerri** [goofball222/factorio#26]
Please, add `arm64` build support.

**Comment by goofball222** [comment]
Hi, unfortunately this is a cantfix/wontfix issue. The Factorio binaries released by the developers are compiled only for X86/amd64 arch and even if I had buildx create an arm64 image the headless server binary itself won't run. Additionally although there are ways to emulate X86/amd64 on arm64, but they're not very suitable or stable enough at this point for a Factorio game server.

**Comment by msrd0** [comment]
Turns out the `factoriotools/factorio` docker container ships with aarch64 support: https://github.com/factoriotools/factorio-docker/blob/master/docker/Dockerfile#L61-L68
