### ISSUE TITLE
Enhancement Request (offer to contribute): Support for Scenarios

### ISSUE THREAD

**Issue by bplein** [goofball222/factorio#3]
(Skipping template because this is more of an offer to contribute)

I'm a current user of another popular factorio container image, and I helped add support to launch a container from a Scenario to that effort. 

I just found out that you have this image, and I'm a fan and user of your Unifi container image. I'd be willing to work on Scenario support by creating an alternate entrypoint that would create the game-save from a scenario (launch with the scenario-entrypoint once to create it, then launch as normal to run it).

If you agree, I'll be happy to work on it (probably just a modified copy of your current entry-point) and submit a pull request.  Let me know!

**Comment by goofball222** [comment]
Sure, feel free to add/enhance and submit pull requests back! My group doesn't use scenarios so it wasn't anything I'd considered to this point.

**Comment by bplein** [comment]
OK, I'll look into it but not rushing to do it. 

It looks like your image requires the use of FACTORIO_OPTS environment variable to start it on an alternate port? I run multiple servers and pass in a specific PORT variable to the current image I'm using, I'll just have to see if my automation works with your image. Then I'll get started on the scenarios thing. 

Basically I have OARC and Railworld, etc. set up as scenarios (I have a couple of others) and I use the scenario entrypoint to create a new map based on those scenarios.

By the way, thank you for maintaining this! I love your Unifi image as well.

**Comment by bplein** [comment]
I've got to switch over to using your image for my servers, going to take a while to update my automation and test it. After that I'll do this. If you would prefer to close this, as I'm the only one asking for it, feel free. It will be a week or more before I can get to it.

**Comment by goofball222** [comment]
Closing aged, some basic scenario support in image already. Please feel free to open pull requests with enhancements.
