### ISSUE TITLE
Pass logs to host /factorio directory

### ISSUE THREAD

**Issue by TiBarification** [goofball222/factorio#34]
Is there any way to add it, so I can access to them without looking up each time to container.

**Comment by nathan-hello** [comment]
You can do this by using `docker-compose logs 2>&1 | tee -a /path/to/file`  from the host machine.

This will write all the logs to the relevant file, and then you can use `tail -f /path/to/file` so that your terminal automatically reads it as the file gets appended with new logs. Hope this helps.

**Comment by TiBarification** [comment]
Looks like crutch, I think better would be to volume these files (factorio-previous.log, factorio-current.log). I used dockerized lgsm , which covers my requirements.
