### ISSUE TITLE
Kubernetes container

### ISSUE THREAD

**Issue by Blackout76** [goofball222/factorio#44]
Im trying to launch your docker image inside my Raspberry Pi cluster by using Kubernetes & portainer (Community Edition 2.19.0)

Error:
Failed to pull image "goofball222/factorio:latest": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/goofball222/factorio:latest": no match for platform in manifest: not found

![image](https://github.com/goofball222/factorio/assets/13513034/f0735626-7ded-47e4-84f9-f6a1371a5b55)

**Comment by oxivanisher** [comment]
I am not a maintainer of this project, but the problem is, that
Factorio itself does not run on ARM CPU's. This is what is meant by
"platform". Factorio does not support Raspberry Pi.

--

Marc Urben

oxi.ch

Am 2023-10-09T17:10:25.000+02:00 hat Blackout76
***@***.***> geschrieben:

**Comment by goofball222** [comment]
As noted there are no ARM binaries for Factorio-headless. It requires x86/amd64.
